name: nutrition-basic
method: POST
path: http://localhost:8080/nutrition
expect:
  status: 200

# Values = One request per value
body:
  product_name:
  # Static = each value to be tested
    #static: 
      values:
        - salmon
        - egg
        - meatballs
        - bread

# LET min, max be fixed
  amount:
    random:
      min: 0
      max: 200

  unit:
    values:
      - GRAM

# List = List of the contents to be sent per request, whole list or sublists per request
  nutrition_fields:
    fields:
    # Stochastic = random subsets of the list for each request
      #stochastic: 
        list:
          - CALORIES
          - FAT
          - SATURATED_FAT
          - TRANS_FAT